### ISSUE TITLE
[Android Bootcamp] Assignment 2: Google Image Search - Ready for review

### ISSUE THREAD

**Issue by cvijayarenu** [cvijayarenu/codepath-weektwo-googleimagesearch#1]
My app is ready for review. "/cc @codepathreview @codepath"

**Comment by codepathreview** [comment]
:+1: nice work. A few notes after checking out the code:
- Good to see you used a filters object to represent the filters to apply to the query
- Properly used spinners (with populated values) to allow users to select filters
- Consider using the [ViewHolder pattern](https://github.com/codepath/android_guides/wiki/Using-an-ArrayAdapter-with-ListView#improving-performance-with-the-viewholder-pattern) to improve performance of photos `GridView`.
- Consider adding the ability to [share an image](http://guides.codepath.com/android/Sharing-Content-with-Intents). This is an important learning for this assignment even though it's optional.
- Nice to see you added the search box to the ActionBar!
- Consider creating a static method in a Helper/Utility class for common methods such as checking for internet
- Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) to your app whenever a network request goes out

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.

**Comment by cvijayarenu** [comment]
Thanks. 
 Will follow the suggestions with the next project.
